# Docker

# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'az-pipeline-terra-dockerhub-service-connection'
        repository: 'sbeyou/semotapi'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(tag)
- stage:
  displayName: 'Infra provisioning on azure ...'
  dependsOn: Build
  jobs:
  - job: 'Provision'
    displayName: 'Provisioning container instance'
    pool:
      vmImage: 'ubuntu-latest'
    variables:
    - group: 'azPipelineTerraPrincipalEnvVars'
    steps:
    - script: |
        set e
        terraform init -input=false
        terra apply -input=false -auto-approve
      name: 'RunTerraform'
      displayName: 'Run Terraform'
      env:
        ARM_CLIENT_ID: $(ARM_CLIENT_ID)
        ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
        ARM_TENANT_ID: $(ARM_TENANT_ID)
        ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)


    
       
          
